#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Get all activities that were added to the AOSP version of the package.
#@Author: Jake Valletta (jakev)
#@Health: beta
#@Version: 1.0

. dtf_core.sh

db_dir=$(dtf prop get Local db-dir)

if [ -z "$1" ]; then
    echo "Usage: $0 [OPTIONS] <package_name>"
    echo "   OPTIONS:"
    echo "    --all    Perform diff on app AOSP applications"
    exit -1
fi



if [ "$1" == "--all" ]; then

    ORIG_IFS=$IFS        # Save the original IFS
    LINE_IFS=$'\n'$'\r'  # For splitting input into lines
    FIELD_IFS=\|         # For splitting lines into fields

    local_results=$(sqlite3 ${db_dir}/sysapps.db "select project_name from apps where aosp_package=1;")

    IFS=$LINE_IFS
    for LINE in $local_results; do
        IFS=$FIELD_IFS
        FIELDS=( $LINE )
        IFS=$LINE_IFS

        app_name=${FIELDS[0]}
 
        echo "Doing $app_name..."
        ${DTF_BINS}/appdiff.py $app_name activities
    done
    
else
    ${DTF_BINS}/appdiff.py $1 activities
fi

