#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Get an APK (optionally with DEX) from device.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

usage()
{
   echo "Usage $0 OPTIONS <package_name>"
   echo "       OPTIONS:"
   echo "            -o    Pull package's ODEX"
   echo "            -s    Search for package"
   echo "            -p    Pull package"
   echo "            -h    Prints this menu"
   exit 1
}

if [ $# -lt 1 ] ; then
   usage
fi

package=""
search=""
odex=""

#Process the arguments
while getopts hdeo:p:s: opt
do
   case "$opt" in
      h) usage;;
      o) odex=$OPTARG;;
      p) package=$OPTARG;;
      s) search=$OPTARG;;
      \?) usage;;
   esac
done



echo -n "Waiting for device..."
adb wait-for-device

if [ $search ]; then
   echo "Searching for \"${search}\"..."
   adb shell "pm list packages"|grep -i "$search"|awk '{print $1}'
   exit 0
elif [ $package ]; then
   echo "Attempting to pull \"${package}\"..."
   package_path=$(adb shell pm path ${package} | tr -d '\r' |awk -F":" '{print $2}')

   if [ $package_path ]; then
      echo "Found match \"${package_path}\""
      adb pull $package_path
      exit 0
   else
      echo "No packages match the string \"${package}\""
      exit 1
   fi
elif [ $odex ]; then
   echo "Attempting to pull \"${odex}\"'s ODEX file..."
   package_path=$(adb shell pm path ${odex} | tr -d '\r' |awk -F":" '{print $2}'|sed 's/\.apk/\.odex/g')

   if [ $package_path ]; then
      echo "Found match \"${package_path}\""
      adb pull $package_path
      exit 0
   else
      echo "No packages match the string \"${odex}\" or ODEX does not exist"
      exit 1
   fi
fi
