#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Compare the DEX code of a local application to the AOSP equivalent.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

. dtf_core.sh

db_dir=$(dtf prop get Local db-dir)
sdk=$(dtf prop get Info sdk)

if [ -z "$1" ]; then
    echo "Usage: $0 [OPTIONS] <package_name>"
    echo "   OPTIONS:"
    echo "    --all    Perform DEX diff on app AOSP applications"
    exit -1
fi

aosp_db=${DTF_PACKAGES}/aosp-data-${sdk}/dbs/appdexdbs/${1}.db

if [ "$1" == "--all" ]; then

    ORIG_IFS=$IFS        # Save the original IFS
    LINE_IFS=$'\n'$'\r'  # For splitting input into lines
    FIELD_IFS=\|         # For splitting lines into fields

    local_results=$(sqlite3 ${db_dir}/sysapps.db "select project_name from apps where aosp_package=1;")

    IFS=$LINE_IFS
    for LINE in $local_results; do
        IFS=$FIELD_IFS
        FIELDS=($LINE)
        IFS=$LINE_IFS

        app_name=${FIELDS[0]}
  
        echo "Doing $app_name..."
        local_db=${db_dir}/appdexdbs/${app_name}.db

        ${DTF_BINS}/dexdiff.py $local_db $aosp_db
    done
    
else
    local_db=${db_dir}/appdexdbs/${1}.db
    ${DTF_BINS}/dexdiff.py $local_db $aosp_db
fi
