#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Create dexdb for an application or all AOSP applications.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

. dtf_core.sh
. dtf_log.sh

run_command () {

    ${DTF_BINS}/dexdumpsql create "$1" "$2"
}

db_dir=$(dtf prop get Local db-dir)
decoded_aosp_dir=$(dtf prop get Local decoded-aosp-dir)
decoded_oem_dir=$(dtf prop get Local decoded-oem-dir)
system_apps_dir=$(dtf prop get Local system-apps-dir)

mkdir ${db_dir}/appdexdbs 2>/dev/null

if [ "$1" == "create" ]; then

    if [ -z "$2" ]; then
        # Do all AOSP apps!
        echo "Making DEX dbs for all AOSP apps..."

        for app in `ls ${decoded_aosp_dir}/`; do 
            if [ -d "${decoded_aosp_dir}/${app}/smali" ]; then

                if [ -f ${db_dir}/appdexdbs/${app}.db ]; then
                    log_w "Skipping \"${app},\" DB already exists!"
                    continue

                else
                    echo "Doing \"${app}\"..."
                    # First try ODEX.
                    if [ -f ${system_apps_dir}/${app}.odex ]; then
                        run_command "${system_apps_dir}/${app}.odex" "${db_dir}/appdexdbs/${app}.db"
                    else
                        run_command "${system_apps_dir}/${app}.apk" "${db_dir}/appdexdbs/${app}.db" 
                    fi  
                fi
            fi
        done
    elif [ "$2" == "--all" ]; then
        # Do all AOSP apps
        echo "Making DEX dbs for all AOSP apps..."

        for app in `ls ${decoded_aosp_dir}/`; do
            if [ -d "${decoded_aosp_dir}/${app}/smali" ]; then

                if [ -f ${db_dir}/appdexdbs/${app}.db ]; then
                    log_w "Skipping \"${app},\" DB already exists!"
                    continue

                else
                    echo "Doing \"${app}\"..."
                    # First try ODEX.
                    if [ -f ${system_apps_dir}/${app}.odex ]; then
                        run_command "${system_apps_dir}/${app}.odex" "${db_dir}/appdexdbs/${app}.db"
                    else
                        run_command "${system_apps_dir}/${app}.apk" "${db_dir}/appdexdbs/${app}.db"
                    fi
                fi
            fi
        done
        # Do all OEM apps
        echo "Making DEX dbs for all OEM apps..."

        for app in `ls ${decoded_oem_dir}/`; do
            if [ -d "${decoded_oem_dir}/${app}/smali" ]; then

                if [ -f ${db_dir}/appdexdbs/${app}.db ]; then
                    log_w "Skipping \"${app},\" DB already exists!"
                    continue

                else
                    echo "Doing \"${app}\"..."
                    # First try ODEX.
                    if [ -f ${system_apps_dir}/${app}.odex ]; then
                        run_command "${system_apps_dir}/${app}.odex" "${db_dir}/appdexdbs/${app}.db"
                    else
                        run_command "${system_apps_dir}/${app}.apk" "${db_dir}/appdexdbs/${app}.db"
                    fi
                fi
            fi
        done
    else
       app=$2
       echo "Doing \"${app}\"..."
       # First try ODEX.
       if [ -f ${system_apps_dir}/${app}.odex ]; then
           run_command "${system_apps_dir}/${app}.odex" "${db_dir}/appdexdbs/${app}.db"
       else
           run_command "${system_apps_dir}/${app}.apk" "${db_dir}/appdexdbs/${app}.db"  
       fi
    fi
else
    echo "Usage: $0 create [package_name]"
    echo ""
    echo "Note: If [package_name] is not supplied, all AOSP packages are created."
fi
