#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Quickly sign an APK.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.1

. $DTF_CORE
. $DTF_LOG

SRC=${DTF_PACKAGES}/Autosign
ROOT=/

usage()
{
    echo "Usage autosign OPTIONS [unsigned_apk]"
    echo "    OPTIONS:"
    echo "      -o OUT  Output APK name."
    echo "      -k KEY  Sign using specified AOSP key."
    echo "      -h      Show this message."
    echo ""
    echo "    KEYs:"
    echo "    media, platform, shared, testkey, default(*)"
    exit 1
}

if [ $# -lt 1 ] ; then
    usage
fi

out_path=""
key=default

#Process the arguments
while getopts ho:k: opt
do
    case "$opt" in
        h) usage;;
        o) out_path=$OPTARG;;
        k) key=$OPTARG;;
        \?) usage;;
    esac
done

in_path=${@:$OPTIND:1}


relative=$(echo ${in_path} | cut -c1-1)
if [ "$relative" = "$ROOT" ]; then
    in_name=$in_path
else
    in_name=${LAUNCH_DIR}/${in_path}
fi

if [ ! -f "${in_name}" ]; then
    log_e "File '${in_name}' does not exist!"
    exit 1
fi

if [ -z "$out_path" ]; then

    out_path=$(basename "$in_name"|sed 's/\.apk//')-signed.apk
fi

relative=$(echo ${out_path} | cut -c1-1)
if [ "$relative" = "$ROOT" ]; then
    out_name=$out_path
else
    out_name=${LAUNCH_DIR}/${out_path}
fi

log_i "Signing '${in_path}' to '${out_path}'"

java -jar "${SRC}/signapk.jar" "${SRC}/keys/${key}.x509.pem" \
        "${SRC}/keys/${key}.pk8" "${in_name}" "${out_name}"
