#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Sign an application with a test key.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

. $DTF_CORE
. $DTF_LOG

SRC=${DTF_PACKAGES}/Autosign
out=your_app_signed.apk

if [ -z "$1" ]; then
    echo "Usage: autosign your_unsigned_apk [output_file]"
    exit -1
fi

in=$1

if [ ! -z "$2" ]; then
    out=$2
fi

log_i "Signing \"${in}\" to \"${out}\""

java -jar ${SRC}/signapk.jar ${SRC}/testkey.x509.pem ${SRC}/testkey.pk8 ${in} ${out}
