#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Dump details about binder interface.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

. dtf_core.sh

if [ -z "$1" ]; then
    echo "Usage: binderdump [service_name]"
    exit -1
fi

db_dir=$(dtf prop get Local db-dir)

service_name=$1

sql="SELECT s.project
     FROM services s 
     WHERE s.name='$service_name' 
     LIMIT 1"

package=$(sqlite3 ${db_dir}/services.db "${sql}")

if [ ! -z  "${package}" ]; then

    path=$(dtf classsearch --framework -ef ${package} |sed 's/\.smali//')

    if [ -z "${path}" ]; then
        echo "Couldn't find source files for service '${service_name}'!"
    else
        echo $path
        ${DTF_BINS}/binderdump.py $path
    fi
else
    echo "Service '${service_name}' not found!"
fi
