#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Starts a drozer session on the device (requires Drozer install).
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

command -v drozer >/dev/null 2>&1 || \
    { echo "\`drozer\` command not found in path. Is it installed?"; exit -1; }

# Make sure we can get to our device.
echo "Waiting for device..."
adb wait-for-device

# Set up the port forward rules
adb forward tcp:31415 tcp:31415

drozer console connect
