#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Attempt to find the implementation of a system service.
#@Author: Jake Valletta (jakev)
#@Health: beta
#@Version: 1.0

. $DTF_CORE

cd $TOP

full_class=$(dtf sysservicedb dump $1|head -n1|awk '{print $3}' |sed 's/(\|)//g')

smali_class="L"$(echo $full_class|sed 's/\./\//g')"\$Stub"

grep -rl "super.*${smali_class}" ./unframework 2>/dev/null 
