#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Convert a framework DEX JAR to a Java JAR for importing into Eclipse.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.1

. $DTF_CORE
. $DTF_LOG

do_framework()
{
    fw=$1

    log_i "Converting \"${fw}\"..."
    dex_full_path=${java_framework_dir}/${fw}.dex

    dtf_smali -o "${dex_full_path}" -a ${sdk} "${unframework_dir}/${fw}/" >/dev/null 2>&1

    rtn=$?
    if [ "$rtn" != "0" ]; then
        log_e "Error smali'ing framework! rtn = ${rtn}"
        exit -1
    fi

    dtf_dex2jar -o "${java_framework_dir}/${fw}.jar" "${dex_full_path}" >/dev/null 2>&1

    rtn=$?
    if [ "$rtn" != "0" ]; then
        log_e "Error using dex2jar on framework DEX! rtn = ${rtn}"
        exit -2
    fi

    # Clean up.
    rm "${dex_full_path}"
}

name=framework2jar
java_framework_dir=java-framework-dir
unframework_dir=$(dtf prop get Local unframework-dir)
sdk=$(dtf prop get Info sdk)

if [ -z $unframework_dir ]; then
    echo "[ERROR] Unable to find unframework directory. Have you unpacked the framework resources?"
    exit -1
fi

mkdir ${java_framework_dir} 2> /dev/null

# Single Mode
if [ -z "$1" ]; then
    echo "Usage: $name [--all] framework_name"
    exit -2
elif [ "$1" == "--all" ]; then

    log_i "Doing all framework files."
    for fw in `ls "${unframework_dir}"`; do
        do_framework $fw
    done
else
    fw=$1
    if [ -d "${unframework_dir}/${fw}/" ]; then
        do_framework $fw
    else
        echo "[ERROR] Framework resource for file '${fw}' not found."
        exit -3
    fi
fi

dtf prop set Local java-framework-dir "${java_framework_dir}"
