#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Compare the DEX code of a local framework to the AOSP equivalent.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

. dtf_core.sh

if [ -z "$1" ]; then
    printf 'Usage: %s <AOSP_framework_name>\n' ${0}
    exit -1
fi

db_dir=$(dtf prop get Local db-dir)
sdk=$(dtf prop get Info sdk)

local_db=${db_dir}/frameworkdexdbs/${1}.db
aosp_db=${DTF_PACKAGES}/aosp-data-${sdk}/dbs/frameworkdexdbs/${1}.db

${DTF_BINS}/dexdiff.py $local_db $aosp_db
