#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Get a listing of OEM added framework files.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

print_nonboot=1
print_boot=1

if [ "$1" == "-nonboot" ]; then
   print_boot=0
elif [ "$1" == "-boot" ]; then
   print_nonboot=0
fi

db_dir=$(dtf prop get Local db-dir)

local_results=$(sqlite3 ${db_dir}/frameworks.db "select name,is_bcp from frameworks where is_aosp=0;")

ORIG_IFS=$IFS        # Save the original IFS
LINE_IFS=$'\n'$'\r'  # For splitting input into lines
FIELD_IFS=\|         # For splitting lines into fields

# Print the non-BOOTCLASSPATH first.
if [ $print_nonboot -eq 1 ]; then
    echo "OEM added non-BOOTCLASSPATH framworks:"

    IFS=$LINE_IFS
    for LINE in $local_results; do
        IFS=$FIELD_IFS
        FIELDS=($LINE)
        IFS=$LINE_IFS

        if [ "${FIELDS[1]}" == "0" ]; then
            echo -e "   "${FIELDS[0]}
        fi
    done
fi

# Print the BOOTCLASSPATH 
if [ $print_boot -eq 1 ]; then
    echo "OEM added BOOTCLASSPATH frameworks:"

    IFS=$LINE_IFS
    for LINE in $local_results; do
        IFS=$FIELD_IFS
        FIELDS=($LINE)
        IFS=$LINE_IFS

        if [ "${FIELDS[1]}" == "1" ]; then
            echo -e "   "${FIELDS[0]}
        fi
    done
fi
