#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Pull all framework JARs (and ODEX files) and framework resources to project directory.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

. dtf_log.sh
. dtf_core.sh

framework_dir=framework

log_i "Pulling all framework files..."

mkdir ${framework_dir} 2> /dev/null

adb pull /system/framework/ ${framework_dir}/

dtf prop set Local framework-dir "${framework_dir}"

log_i "Framework pull complete!"
