#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Get app system libraries off the device.
#@Author: Jake Valletta (jakev)
#@Health: broken
#@Version: 1.0

system_libs=system-libs

mkdir ${system_libs} 2>/dev/null

adb pull /system/lib ${system_libs}
adb pull /vendor/lib ${system_libs}

dtf prop set Local system-libs-dir "${system_libs}"
