#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Installs Drozer APK on the test device.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

. dtf_core.sh
. dtf_log.sh

drozer_apk=${DTF_PACKAGES}/Drozer/drozer-agent-2.3.2.apk
drozer_package=com.mwr.dz

usage()
{
    echo "Usage: installdrozer [-r]"
    echo ""
    echo "  -r     Force reinstall."
}

install_drozer()
{
    log_i "Installing Drozer..."

    # See if .drozer already exists
    if [ ! -d .drozer ]; then
        log_i "Installing drozer files to \".drozer\"..."
         mkdir .drozer 2>/dev/null
         dtf_apktool d "${drozer_apk}" -f -o .drozer/ > /dev/null 2>&1
         cp "${DTF_PACKAGES}/Drozer/Makefile" .drozer/
    else
        log_w "The directory \".drozer\" already exists, skipping copy"
    fi

    adb install ${drozer_apk}

    log_i "Setting up forwarding..."
    adb forward tcp:31415 tcp:31415

    log_i "Drozer installed."
}

if [ "$1" == "-h" ]; then
    usage
    exit 0
fi

echo -n "Please connect your device..."
adb wait-for-device
echo "OK"

# First find out if Drozer is installed
installed=$(adb shell pm list packages ${drozer_package})

if [ "$1" == "-r" ]; then
    
    if [ -z "$installed" ]; then
        log_e "Drozer is not installed, exiting!"
        exit -2
    fi

    if [ ! -z "$2" ]; then
        drozer_apk=$2
    fi

    log_i "Reinstalling Drozer..."
    adb uninstall ${drozer_package}
    install_drozer ${drozer_apk}
    exit 0
fi

if [ ! -z "$installed" ]; then
    log_i "Drozer is already installed, exiting!"
    exit -1
fi

if [ ! -z "$1" ]; then
        drozer_apk=$1
fi

install_drozer ${drozer_apk}
exit 0
