#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Get information about a shared library ("SO").
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.1

. dtf_log.sh

print_info()
{
	lib_name=$(pwd)/$1

    echo "Doing : ${lib_name}"

	echo "Dev grep:"
	grep -rEo --text "/dev/([a-zA-Z0-9_\-\.]*[/]?)*" ${lib_name}
	objdump -T ${lib_name} 2>/dev/null |grep socket >/dev/null&& echo "[INFO] Imports socket!"
	objdump -T ${lib_name} 2>/dev/null |grep ioctl >/dev/null&& echo "[INFO] Imports ioctl!"
	nm -D ${lib_name} 2>/dev/null|grep "T Java_"
}

if [ "$1" == "-d" ] && [ ! -z "$2" ]; then

    dir=$2

    if [ ! -d "${dir}" ]; then
        echo "Directory ${dir} does not exist. Exiting."
        exit -1
    fi

    for file in `find "${dir}"`; do
        print_info $file
    done


elif [ ! -z "$1" ]; then

    print_info $1

else
    echo "Usage: $0 [-d] lib_name"
fi
