#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Copy a blank, compiled, application for building.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

. $DTF_CORE
. $DTF_LOG

if [ -z "$1" ]; then
    echo "Usage: $0 [-s] <new_project_dir>"
    exit -1
fi

if [[ "$1" == "-s" && ! -z "$2" ]]; then
    
    log_i "Creating new app (with source) at '${2}'"
    mkdir "$2" 2>/dev/null
    cp -r "${DTF_PACKAGES}/HelloWorld_app/HelloWorld/"* "$2"
    cp -r "${DTF_PACKAGES}/HelloWorld_app/src/" "$2"
    exit 0
fi 

log_i "Creating new app at '${1}'"
mkdir "$1" 2>/dev/null
cp -r "${DTF_PACKAGES}/HelloWorld_app/HelloWorld/"* "$1"

exit 0
