#!/usr/bin/env python
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Protected Broadcast Listing"""

import dtf.properties as prop
from dtf.module import Module

import AppDb

class pbroadcasts(Module):

    """Module class for listing protected broadcasts"""

    about = 'Print protected broadcast actions.'
    author = 'Jake Valletta (jakev)'
    health = 'beta'
    name = 'pbroadcasts'
    version = '1.0'
  
    def execute(self, args):
  
        """Main module executor"""
        project_db_path = prop.get_prop("Local", "db-dir") + "/sysapps.db"

        appdb = AppDb.AppDb(project_db_path)

        for app in appdb.getProtectedActions():
            print app
