#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Simple permision printer.
#@Author: Jake Valletta (jakev)
#@Health: working
#@Version: 1.1

permission=$1

sqlite3 .dbs/sysapps.db "select permissions.id,permissions.name, permissions.protection_level, apps.project_name, apps.package_name from permissions join apps on permissions.application_id=apps.id" |grep "$permission"
