#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Reset the serial to the currently connected device.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

echo -n "Please connect the test device, and only the test device (press any key to continue) "
read _

unset ANDROID_SERIAL

echo "Restarting ADB..."
adb kill-server && adb start-server > /dev/null

echo "Waiting for a device to be connected..."
adb wait-for-device

serial=$(adb devices | grep -E "device$" |awk '{print $1}')

echo -n "Got serial ${serial}, is this correct? [Y/n] "
read res

if [ "$res" = "n" ]; then
   echo "Bailing!"
   exit -4
fi

dtf prop set Info serial "${serial}"
