#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Send an android_secret_code broadcast.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.1

SECRET_CODE_ACTION=android.provider.Telephony.SECRET_CODE
SECRET_CODE_SCHEME=android_secret_code

if [ -z "$1" ]; then
    echo "Usage: $0 <secret_code> [user]"
    echo "    secret_code  Secret code intent data to send."
    echo "    user         Send intent as the specified user (optional)."
    exit -1
fi

secretcode=$1
user=$2

adb wait-for-device

if [[ -z $user ]]; then
    echo "Sending secret code \"${secretcode}\"..."
    adb shell "am broadcast -a ${SECRET_CODE_ACTION} -d ${SECRET_CODE_SCHEME}://${secretcode}"
else
    echo "Sending secret code \"${secretcode}\" as user \"${user}\"..."
    adb shell "run-as ${user} am broadcast -a ${SECRET_CODE_ACTION} -d ${SECRET_CODE_SCHEME}://${secretcode}"
fi
