#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Find all shared ID occurances for a give useSharedId string.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

do_search()
{

    IFS=$'\r\n' filenames=($( grep -rEo "sharedUserId=\"[a-zA-Z0-9\.]*\"" ${1}/*/AndroidManifest.xml | awk -F\: '{print $1}'| sed 's/\/AndroidManifest\.xml//g'|sed "s/${1}\///g"))
    IFS=$'\r\n' shared_id=($( grep -rEo "sharedUserId=\"[a-zA-Z0-9\.]*\"" ${1}/*/AndroidManifest.xml | awk -F\: '{print $2}'|tr -d \"|
    sed 's/sharedUserId=//g'))

    i=0
    for item in "${shared_id[@]}"
    do
        if [[ "$item" =~ "$search_shared_id" ]]; then
            echo "   [+] ${filenames[$i]} (${item})"
        fi

        i=`expr $i + 1`
    done
}

. dtf_core.sh


if [ -z "$1" ]; then

    echo "Usage: sharedid <shared_id_string>"
    exit -1
fi

search_shared_id="$1"

echo "AOSP Shared:"
do_search "decoded-aosp"


echo "OEM Shared:"
do_search "decoded-oem"
