#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Get a listing of OEM added system applications (diff the AOSP).
#@Author: Jake Valletta (jakev)
#@Health: broken
#@Version: 1.0

. dtf_core.sh

sdk=$(dtf prop get Info sdk)
db_dir=$(dtf prop get Local db-dir)

syslist_file=$DTF_PACKAGES/aosp-data-${sdk}/sysapplist
local_sysappdb=${db_dir}/sysapps.db


IFS=$'\n' aosp_sysapps=($(cat ${syslist_file}))
silent=0

if [ "$1" == "-q" ]; then
    silent=1
fi

[[ "$silent" == "0" ]] && echo "Finding potential OEM applications (may not be 100% accurate)..."

sqlite3 "$local_sysappdb" "SELECT package_name, project_name FROM apps;" | while read line; do

    package_name=$(echo $line |awk -F\| '{print $1}')
    project_name=$(echo $line |awk -F\| '{print $2}')

    rtn=$(containsElement "${project_name}" "${aosp_sysapps[@]}")

    if [ "${rtn}" == "0" ]; then
        if [ "$silent" == "1" ]; then
            echo ${project_name}
        else
            echo "${project_name} (${package_name})"
        fi
    fi
done
