#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: List OEM added system libraries.
#@Author: Jake Valletta (jakev)
#@Health: broken
#@Version: 1.0

. $DTF_CORE

sdk=$(dtf prop get Info sdk)
system_libs_dir=$(dtf prop get Local system-libs-dir)

aosp_syslib_file=${DTF_PACKAGES}/aosp-data-${sdk}/systemlibraries

IFS=$'\r\n' aosp_array=($(cat ${aosp_syslib_file}))

IFS=$'\r\n' local_array=($(find ${system_libs_dir} -type f |sed 's/^\.\///g'| sed "s/^${system_libs_dir}\///g"))

for lib in "${local_array[@]}"; do

    rtn=$(containsElement "${lib}" "${aosp_array[@]}")

        if [ "${rtn}" == "0" ]; then
 
            lib_path=${system_libs_dir}/${lib}

            echo "New library: ${lib_path}"

            dtf libinfo "${lib_path}"
            echo ""
        fi

done



