#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2015 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Get list of applications installed by a user (JB+).
#@Author: Jake Valletta (jakev)
#@Health: beta
#@Version: 1.0

. dtf_core.sh
. dtf_log.sh

sdk=$(dtf prop get Info sdk)

if [ $sdk -lt $JELLY_BEAN ]; then
    echo "This module only works with Jelly Bean or newer devices!"
    exit -1
fi

adb wait-for-device

echo "Installer|Package Name"
adb shell pm list packages -u -3 -i|sed 's/\r//g'|sed 's/\(package:\|installer=\)//g'|awk '{print $2"|"$1}'|\
sed 's/com\.android\.vending/Google Play/g'|sort

