#!/usr/bin/env bash
# DTF Core Content
# Copyright 2013-2014 Jake Valletta (@jake_valletta)
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#@About: Just a sample <uses-permission> generator.
#@Author: Jake Valletta (jakev)
#@Health: stable
#@Version: 1.0

. dtf_core.sh

get_all()
{
    db_dir=$(dtf prop get Local db-dir)

    sql="SELECT p.name
         FROM permissions p
         WHERE p.protection_level='normal' OR p.protection_level='dangerous';"

    ORIG_IFS=$IFS        # Save the original IFS
    LINE_IFS=$'\n'$'\r'  # For splitting input into lines
    FIELD_IFS=\|         # For splitting lines into fields

    local_results=$(sqlite3 ${db_dir}/sysapps.db "${sql}")

    IFS=$LINE_IFS
    for LINE in $local_results; do
        IFS=$FIELD_IFS
        FIELDS=($LINE)
        IFS=$LINE_IFS

        name=${FIELDS[0]}
  
        print_perm "$name"
    done
}

print_file()
{
    echo ""
    while read p; do
        print_perm "${p}"
    done < "$1"
    echo ""
}

print_perm()
{
    perm=$1

    if [ -z "$perm" ]; then
        echo "No perm!"
        return
    fi

    echo "    <uses-permission android:name=\"${perm}\" />"
}

if [ -z "$1" ]; then
    PERM=com.jakev.MYPERM
elif [ "$1" == "-f" ] && [ ! -z "$2" ]; then
    print_file $2
elif [ "$1" == "--all" ]; then
    get_all
else
    echo ""
    print_perm "$1"
    echo ""
fi
